"""Add budget column to User model

Revision ID: 993de082c038
Revises: 
Create Date: 2024-03-28 15:50:26.467214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '993de082c038'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('budget')

    # ### end Alembic commands ###
