"""Light(int) - change, Motion(int) - add 

Revision ID: c0f012473489
Revises: 129572aca3ae
Create Date: 2024-04-02 17:31:49.839183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0f012473489'
down_revision = '129572aca3ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motion', sa.Integer(), nullable=True))
        batch_op.alter_column('light',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stats', schema=None) as batch_op:
        batch_op.alter_column('light',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.drop_column('motion')

    # ### end Alembic commands ###
